### ISSUE TITLE
Can not log in after using the editor

### ISSUE THREAD

**Issue by FelixEnd** [BPTeam11/web-sharelatex#18]
I used sharelatex, done stuff in the editor and then logged out. Then I restarted the server and every time I tried to log in the server crashed.

EDIT: the server does not need to be restarted. Logging out and logging in again crashes it.
Note: I assume this may be difficult because it could be related to very early changes Max or I did, so I recommend that either Max or I work on this.

**Comment by pkonow** [comment]
Confirmed. Server prints the following message:

[2015-03-06T19:09:24.600Z] ERROR: web-sharelatex/18212 on localhost.localdomain: error passed to top level next middlewear (url=/login, method=POST)
    Error: Forbidden
      at Object.exports.error (/home/user/code/bp/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
      at /home/user/code/bp/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
      at Object.handle (/home/user/code/bp/sharelatex/web/app/js/infrastructure/Server.js:117:14)
      at next (/home/user/code/bp/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at Object.handle (/home/user/code/bp/sharelatex/web/app/js/infrastructure/Server.js:107:14)
      at next (/home/user/code/bp/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
      at next (/home/user/code/bp/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:312:9)
      at /home/user/code/bp/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:329:9
      at /home/user/code/bp/sharelatex/web/node_modules/connect-redis/lib/connect-redis.js:93:25
      at try_callback (/home/user/code/bp/sharelatex/web/node_modules/redis-sharelatex/node_modules/redis/index.js:592:9)
      at RedisClient.return_reply (/home/user/code/bp/sharelatex/web/node_modules/redis-sharelatex/node_modules/redis/index.js:685:13)
      at ReplyParser.<anonymous> (/home/user/code/bp/sharelatex/web/node_modules/redis-sharelatex/node_modules/redis/index.js:321:14)
      at ReplyParser.emit (events.js:95:17)
      at ReplyParser.send_reply (/home/user/code/bp/sharelatex/web/node_modules/redis-sharelatex/node_modules/redis/lib/parser/javascript.js:300:10)
      at ReplyParser.execute (/home/user/code/bp/sharelatex/web/node_modules/redis-sharelatex/node_modules/redis/lib/parser/javascript.js:203:22)
      at RedisClient.on_data (/home/user/code/bp/sharelatex/web/node_modules/redis-sharelatex/node_modules/redis/index.js:547:27)
      at Socket.<anonymous> (/home/user/code/bp/sharelatex/web/node_modules/redis-sharelatex/node_modules/redis/index.js:102:14)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
